import './js/swiper.js';
import './js/modal_explore_our_new.js';
// import './js/buy_now.js';
import './js/mobile-menu.js';
import './js/leave_a_review_about.js';
import './js/buy_now_hero.js';
import './js/video.js';
import './js/slick.min.js';
import './js/script.js';
import './js/buy_now_sellers.js';
